### PR TITLE
Migrate CI to Github Large Runner

### PR DESCRIPTION
**Pull request by Ninja3047**

### CODE REVIEW

**Comment by Ninja3047** [comment]
Should be passing most of checks, i think a few need some more work

**Comment by frabert** [comment]
I think the AWS-related secrets can be removed

**Comment by Ninja3047** [comment]
Ah yeah, wasn't sure if we still wanted to upload the test artifacts to s3
CC @artemdinaburg

**Comment by Ninja3047** [comment]
AWS related secrets are DO spaces credentials that we upload artifacts to through their S3 compatible API

**Review by frabert — APPROVED** [review]

**Pull request merged**
