### PR TITLE
Handle Phi nodes directly

### PR DESCRIPTION
**Pull request by frabert**
Angha is still using the `--remove-phi-nodes` flag

### CODE REVIEW

**Review by pgoodman — APPROVED** [review]

**Comment by pgoodman** [comment]
Is `--remove-phi-nodes` requried for Angha tests?

**Comment by frabert** [comment]
I don't think so, but I couldn't find a quick n easy way to change the bench settings without having to fork the CI repo & updating the submodule reference

**Comment by pgoodman** [comment]
Ahhhh. Is it available on amp-web now?

**Comment by frabert** [comment]
It is now

**Pull request merged**
